# Generated by Django 3.2.13 on 2022-04-27 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('constraints', models.TextField()),
                ('inputformat', models.TextField()),
                ('outputformat', models.TextField()),
                ('sampleinput1', models.TextField()),
                ('sampleoutput1', models.TextField()),
                ('sampleinput2', models.TextField()),
                ('sampleoutput2', models.TextField()),
                ('sampleinput3', models.TextField()),
                ('sampleoutput3', models.TextField()),
                ('testcases', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
