# Generated by Django 3.2.13 on 2022-04-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='memory_limits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limits',
            field=models.IntegerField(default=0),
        ),
    ]
