# Generated by Django 3.2.13 on 2022-04-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0002_auto_20220428_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answers',
            field=models.TextField(default='n'),
        ),
    ]
