# Generated by Django 3.2.13 on 2022-04-28 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0003_problem_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.TextField()),
                ('submitteddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(max_length=200)),
            ],
        ),
    ]
