# Generated by Django 3.2.13 on 2022-04-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0005_auto_20220429_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='language',
            field=models.CharField(default='python3', max_length=200),
        ),
    ]
