# Generated by Django 3.2.13 on 2022-04-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0006_problem_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='language',
        ),
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(default='python3', max_length=200),
        ),
    ]
