# Generated by Django 3.2.13 on 2022-05-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0007_auto_20220429_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='testinput1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testinput2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testinput3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testinput4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testinput5',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testoutput1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testoutput2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testoutput3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testoutput4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testoutput5',
            field=models.TextField(null=True),
        ),
    ]
